version: "3.3"
services:
  postgres:
    image: postgres
    ports:
      - 5455:${POSTGRES_PORT}
    networks: [backing-services]
    volumes: ["postgres-data:/var/lib/postgresql/data"]
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
volumes:
  postgres-data: {}
networks:
  backing-services:
    driver: bridge